<<<<<<< HEAD
kname: CI
=======
name: CI
>>>>>>> 19c9cfa (Init CI/CD: app FastAPI, tests, Docker, workflows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

<<<<<<< HEAD
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
=======
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
>>>>>>> 19c9cfa (Init CI/CD: app FastAPI, tests, Docker, workflows)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
<<<<<<< HEAD
          python-version: "3.12"
=======
          python-version: '3.11'
>>>>>>> 19c9cfa (Init CI/CD: app FastAPI, tests, Docker, workflows)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

<<<<<<< HEAD
      - name: Lint with ruff
        run: ruff check .

      - name: Run tests with coverage (fix working directory)
        run: |
          cd $GITHUB_WORKSPACE/ci-cd_BAMEKA
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          echo "Current directory: $(pwd)"
          echo "Python path: $PYTHONPATH"
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=term-missing --cov-fail-under=80

=======
      - name: Lint (ruff)
        run: ruff check .

      - name: Run tests with coverage (fail if <80%)
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=app --cov-report=term-missing --cov-fail-under=80
>>>>>>> 19c9cfa (Init CI/CD: app FastAPI, tests, Docker, workflows)
